### ISSUE TITLE
Web Speech CodeSamplez

### ISSUE THREAD

**Issue by natemunk** [ranacseruet/webspeech#5]
Hey Rana, 

I loved your tutorial for web speech. I created one following your tutorial on CodeSamplez.com. It was straight forward and worked well. It stopped working recently because the js files hosted on codesamples became unavailable. 

http://demo.codesamplez.com/scripts/index.js
http://demo.codesamplez.com/scripts/libraries/javascriptmvc/steal.production.js
http://demo.codesamplez.com/bower_components/webspeech/src/webspeech.js
http://demo.codesamplez.com/bower_components/platform/platform.js

These are the files that can no longer be accessed and  caused the code to break. I was able to find some of them on git and others I couldn't find. Do you have those files available?

**Comment by ranacseruet** [comment]
Sounds like you faced a temporary outage of my site? They are working fine for me now. Please open another ticket if you continue to face the issue.
